import { AppDatabase, InspectionMeta, CertificateItem, DeficiencyItem, AuditLogEntry, InspectionSheetData } from './types';

export const initialMasterCalendar: InspectionMeta[] = [
  {
    id: 'fixed-fire',
    title: 'Fixed Fire Systems',
    frequency: 'Monthly',
    department: 'Deck / Vendor',
    regBasis: '46 CFR 189.25-20(a)(2); 46 CFR 147.65',
    lastCompleted: '2026-07-15',
    nextDue: '2026-08-15',
    daysRemaining: 6,
    status: 'Current',
    mateOic: '2nd Mate / Chief Engineer',
    notes: 'Crew visual inspection; annual vendor service record included',
    openDeficienciesCount: 0,
  },
  {
    id: 'weekly-lifesaving',
    title: 'Weekly Lifesaving',
    frequency: 'Weekly',
    department: 'Deck',
    regBasis: '46 CFR 199.190(d); SMS weekly lifesaving',
    lastCompleted: '2026-08-03',
    nextDue: '2026-08-10',
    daysRemaining: 1,
    status: 'Due Soon',
    mateOic: '3rd Mate',
    notes: 'Weekly liferafts, rescue boat quick checks',
    openDeficienciesCount: 0,
  },
  {
    id: 'lifesaving-monthly',
    title: 'Lifesaving Monthly',
    frequency: 'Monthly',
    department: 'Deck',
    regBasis: 'Lifesaving appliances monthly inspection',
    lastCompleted: '2026-07-12',
    nextDue: '2026-08-12',
    daysRemaining: 3,
    status: 'Due Soon',
    mateOic: '3rd Mate',
    notes: 'Liferafts, lifebuoys, and lifesaving equipment',
    openDeficienciesCount: 0,
  },
  {
    id: 'pyrotechnics-locker',
    title: 'Pyrotechnics Locker',
    frequency: 'Monthly',
    department: 'Deck',
    regBasis: 'Pyrotechnics and line-throwing appliances',
    lastCompleted: '2026-07-14',
    nextDue: '2026-08-14',
    daysRemaining: 5,
    status: 'Current',
    mateOic: '2nd Mate',
    notes: 'Dedicated pyrotechnics locker and bridge pyro checks',
    openDeficienciesCount: 0,
  },
  {
    id: 'rescue-boat',
    title: 'Rescue Boat Monthly',
    frequency: 'Monthly',
    department: 'Deck',
    regBasis: 'Rescue boat monthly inspection',
    lastCompleted: '2026-07-10',
    nextDue: '2026-08-10',
    daysRemaining: 1,
    status: 'Due Soon',
    mateOic: 'Chief Mate / 3rd Mate',
    notes: 'Detailed rescue boat and operational checks',
    openDeficienciesCount: 1,
  },
  {
    id: 'lifejackets-immersion',
    title: 'Lifejackets Immersion',
    frequency: 'Monthly',
    department: 'Deck',
    regBasis: 'Lifejackets / immersion suits inventory',
    lastCompleted: '2026-07-16',
    nextDue: '2026-08-16',
    daysRemaining: 7,
    status: 'Current',
    mateOic: '3rd Mate',
    notes: 'Location counts, spares, and condition',
    openDeficienciesCount: 0,
  },
  {
    id: 'dewatering-pumps',
    title: 'De-Watering Pumps',
    frequency: 'Monthly',
    department: 'Engineering',
    regBasis: 'Dewatering pump inspection',
    lastCompleted: '2026-07-08',
    nextDue: '2026-08-08',
    daysRemaining: -1,
    status: 'Overdue',
    mateOic: '1st Asst Engineer',
    notes: 'Pumps, hoses, strainers, fuel/oil, and operational test',
    openDeficienciesCount: 1,
  },
  {
    id: 'fire-stations',
    title: 'Fire Stations',
    frequency: 'Monthly',
    department: 'Deck',
    regBasis: 'Fire hose stations monthly',
    lastCompleted: '2026-07-18',
    nextDue: '2026-08-18',
    daysRemaining: 9,
    status: 'Current',
    mateOic: '2nd Mate',
    notes: 'Fire hose station condition and missing/defective items',
    openDeficienciesCount: 0,
  },
  {
    id: 'turnout-gear',
    title: 'Turnout Gear SCBA',
    frequency: 'Monthly',
    department: 'Deck',
    regBasis: 'Fire outfits, SCBA, multi-gas analyzers',
    lastCompleted: '2026-07-11',
    nextDue: '2026-08-11',
    daysRemaining: 2,
    status: 'Due Soon',
    mateOic: '2nd Mate',
    notes: 'Packs, multi-gas analyzers, and SCBA sections',
    openDeficienciesCount: 0,
  },
  {
    id: 'damage-control',
    title: 'Damage Control Gear',
    frequency: 'Monthly',
    department: 'Deck',
    regBasis: 'Damage control gear tracked',
    lastCompleted: '2026-07-20',
    nextDue: '2026-08-20',
    daysRemaining: 11,
    status: 'Current',
    mateOic: 'Chief Mate',
    notes: 'Damage control gear condition check',
    openDeficienciesCount: 0,
  },
  {
    id: 'fire-extinguishers',
    title: 'Fire Extinguishers',
    frequency: 'Monthly',
    department: 'Deck / Vendor',
    regBasis: 'Portable extinguisher monthly inspection',
    lastCompleted: '2026-07-13',
    nextDue: '2026-08-13',
    daysRemaining: 4,
    status: 'Due Soon',
    mateOic: '2nd Mate',
    notes: 'Dry chem rotation and condition checks',
    openDeficienciesCount: 1,
  },
  {
    id: 'dg-locker',
    title: 'DG Locker Monthly',
    frequency: 'Monthly',
    department: 'Deck',
    regBasis: 'DG/Hazmat locker with firefighting',
    lastCompleted: '2026-07-19',
    nextDue: '2026-08-19',
    daysRemaining: 10,
    status: 'Current',
    mateOic: 'Chief Mate',
    notes: 'DG/Hazmat locker, fixed system, extinguishers, labels, segregation',
    openDeficienciesCount: 0,
  },
  {
    id: 'eebd',
    title: 'EEBD',
    frequency: 'Monthly',
    department: 'Deck/Eng',
    regBasis: 'EEBD inspection',
    lastCompleted: '2026-07-17',
    nextDue: '2026-08-17',
    daysRemaining: 8,
    status: 'Current',
    mateOic: '3rd Mate / 2nd Asst Eng',
    notes: 'Location, serial number, exp date, needle/condition',
    openDeficienciesCount: 0,
  },
  {
    id: 'eyewash-firstaid',
    title: 'Eye Wash Decon First Aid',
    frequency: 'Monthly',
    department: 'Deck/Medical',
    regBasis: 'Eye wash, first aid, washdown stations',
    lastCompleted: '2026-07-22',
    nextDue: '2026-08-22',
    daysRemaining: 13,
    status: 'Current',
    mateOic: 'Medical Officer / 3rd Mate',
    notes: 'Restock, exp date, and flow/mechanical checks',
    openDeficienciesCount: 0,
  },
  {
    id: 'watertight-doors',
    title: 'Watertight Doors',
    frequency: 'Weekly',
    department: 'Deck/Eng',
    regBasis: 'Watertight closure inspection',
    lastCompleted: '2026-08-04',
    nextDue: '2026-08-11',
    daysRemaining: 2,
    status: 'Due Soon',
    mateOic: 'Chief Mate / Chief Eng',
    notes: 'Watertight doors and hatches inspection',
    openDeficienciesCount: 0,
  },
  {
    id: 'gmdss-bridge',
    title: 'GMDSS Bridge Safety',
    frequency: 'Daily',
    department: 'Deck',
    regBasis: 'GMDSS / bridge safety log',
    lastCompleted: '2026-08-09',
    nextDue: '2026-08-10',
    daysRemaining: 1,
    status: 'Current',
    mateOic: 'OIC Watchstander',
    notes: 'Radio, SART, EPIRB, line throwing, bridge pyro',
    openDeficienciesCount: 0,
  },
];

export const initialDeficiencyLog: DeficiencyItem[] = [
  {
    id: 'DEF-2026-001',
    dateFound: '2026-07-10',
    inspectionId: 'rescue-boat',
    inspectionTitle: 'Rescue Boat Monthly',
    deficiency: 'Rescue boat search light lens cracked; water condensation inside housing',
    priority: 'Medium',
    workOrder: 'WO-88210',
    assignedTo: 'Deck Dept - 3rd Mate',
    dueDate: '2026-08-15',
    dateCorrected: '',
    verifiedBy: '',
    status: 'In Progress',
    notes: 'Replacement housing ordered from vendor. Temporary seal applied.',
    initials: 'SM',
  },
  {
    id: 'DEF-2026-002',
    dateFound: '2026-07-08',
    inspectionId: 'dewatering-pumps',
    inspectionTitle: 'De-Watering Pumps',
    deficiency: 'PROSSER 2 pump discharge hose gasket worn and leaking slightly during pressure test',
    priority: 'High',
    workOrder: 'WO-88194',
    assignedTo: 'Eng Dept - 1st Asst',
    dueDate: '2026-08-05',
    dateCorrected: '',
    verifiedBy: '',
    status: 'Open',
    notes: 'Overdue for resolution. Gasket replacement in stock in sci stores.',
    initials: 'RK',
  },
  {
    id: 'DEF-2026-003',
    dateFound: '2026-07-13',
    inspectionId: 'fire-extinguishers',
    inspectionTitle: 'Fire Extinguishers',
    deficiency: 'Extinguisher #14 (5# CO2 in Computer Lab) missing updated inspection tag wire seal',
    priority: 'Low',
    workOrder: 'WO-88240',
    assignedTo: '2nd Mate',
    dueDate: '2026-08-20',
    dateCorrected: '2026-07-14',
    verifiedBy: 'Chief Mate',
    status: 'Resolved',
    notes: 'New tamper seal attached and logged.',
    initials: 'JL',
  },
];

export const initialCertificateRegister: CertificateItem[] = [
  {
    id: 'CERT-001',
    certificateSystem: 'Fixed fire suppression systems',
    vendor: 'Pacific Fire & Marine Protection',
    inspector: 'Capt. Thomas Vance',
    issueDate: '2025-11-10',
    serviceTestDate: '2025-11-10',
    expirationNextDue: '2026-11-10',
    daysRemaining: 93,
    status: 'Current',
    equipmentNotes: 'Co2 cylinders weighed, Ansul hood serviced, remote pulls function tested',
  },
  {
    id: 'CERT-002',
    certificateSystem: 'Portable fire extinguishers',
    vendor: 'Honolulu Safety Services Inc.',
    inspector: 'M. Rivera',
    issueDate: '2025-10-01',
    serviceTestDate: '2025-10-01',
    expirationNextDue: '2026-10-01',
    daysRemaining: 53,
    status: 'Current',
    equipmentNotes: 'Annual certification tag on all 77 active + 18 spare units',
  },
  {
    id: 'CERT-003',
    certificateSystem: 'SCBA bottles / packs',
    vendor: 'Safety Hawaii Equipment',
    inspector: 'D. Chen',
    issueDate: '2025-09-15',
    serviceTestDate: '2025-09-15',
    expirationNextDue: '2026-09-15',
    daysRemaining: 37,
    status: 'Due Soon',
    equipmentNotes: 'Hydrostatic test current for packs A-F & spares',
  },
  {
    id: 'CERT-004',
    certificateSystem: 'Liferafts x6',
    vendor: 'Viking Life-Saving Equipment',
    inspector: 'A. Kimo',
    issueDate: '2025-08-28',
    serviceTestDate: '2025-08-28',
    expirationNextDue: '2026-08-28',
    daysRemaining: 19,
    status: 'Due Soon',
    equipmentNotes: 'Liferafts 1-6 annual repack due soon',
  },
  {
    id: 'CERT-005',
    certificateSystem: 'Life raft embarkation ladders x2',
    vendor: 'Viking Life-Saving Equipment',
    inspector: 'A. Kimo',
    issueDate: '2025-08-28',
    serviceTestDate: '2025-08-28',
    expirationNextDue: '2026-08-28',
    daysRemaining: 19,
    status: 'Due Soon',
    equipmentNotes: 'Rope & step integrity inspection',
  },
  {
    id: 'CERT-006',
    certificateSystem: 'Air compressor sample report',
    vendor: 'Trace Analytics Marine Lab',
    inspector: 'Lab Tech #402',
    issueDate: '2026-05-12',
    serviceTestDate: '2026-05-12',
    expirationNextDue: '2026-08-12',
    daysRemaining: 3,
    status: 'Critical',
    equipmentNotes: 'Breathing air quality certificate (Grade D compliance)',
  },
  {
    id: 'CERT-007',
    certificateSystem: 'Certificate of Inspection (COI)',
    vendor: 'US Coast Guard Sector Honolulu',
    inspector: 'USCG Marine Inspector',
    issueDate: '2025-04-18',
    serviceTestDate: '2026-04-18',
    expirationNextDue: '2027-04-18',
    daysRemaining: 252,
    status: 'Current',
    equipmentNotes: 'Subchapter U / R/V Kilo Moana official USCG COI',
  },
  {
    id: 'CERT-008',
    certificateSystem: 'EPIRB / SART batteries',
    vendor: 'Marine Electronics Oahu',
    inspector: 'J. Silva',
    issueDate: '2024-03-10',
    serviceTestDate: '2024-03-10',
    expirationNextDue: '2027-03-10',
    daysRemaining: 213,
    status: 'Current',
    equipmentNotes: 'EPIRB battery exp Mar 2027; HRU exp Aug 2026',
  },
  {
    id: 'CERT-009',
    certificateSystem: 'GMDSS radio inspection',
    vendor: 'Global Marine Radio Surveyors',
    inspector: 'E. Tanaka',
    issueDate: '2025-12-01',
    serviceTestDate: '2025-12-01',
    expirationNextDue: '2026-12-01',
    daysRemaining: 114,
    status: 'Current',
    equipmentNotes: 'GMDSS Safety Radio Certificate renewal survey',
  },
  {
    id: 'CERT-010',
    certificateSystem: 'Rescue boat annual service',
    vendor: 'Norseman Marine Systems',
    inspector: 'P. Hansen',
    issueDate: '2025-08-20',
    serviceTestDate: '2025-08-20',
    expirationNextDue: '2026-08-20',
    daysRemaining: 11,
    status: 'Due Soon',
    equipmentNotes: 'Outboard & release hook load test certification',
  },
];

export const initialAuditLog: AuditLogEntry[] = [
  {
    id: 'AUD-101',
    inspectionId: 'watertight-doors',
    inspectionTitle: 'Watertight Doors',
    mateName: 'James L.',
    position: 'Chief Mate',
    signatureInitials: 'JL',
    dateCompleted: '2026-08-04',
    timeCompleted: '09:30',
    auditStatus: 'Verified',
    dueDate: '2026-08-11',
    notes: 'All 14 doors and hatches operational. PA & General alarm test SAT.',
  },
  {
    id: 'AUD-102',
    inspectionId: 'weekly-lifesaving',
    inspectionTitle: 'Weekly Lifesaving',
    mateName: 'Sarah M.',
    position: '3rd Mate',
    signatureInitials: 'SM',
    dateCompleted: '2026-08-03',
    timeCompleted: '14:15',
    auditStatus: 'Verified',
    dueDate: '2026-08-10',
    notes: 'Pelican hooks & HRUs clear. Rescue boat engine flushed.',
  },
  {
    id: 'AUD-103',
    inspectionId: 'gmdss-bridge',
    inspectionTitle: 'GMDSS Bridge Safety',
    mateName: 'David K.',
    position: '2nd Mate',
    signatureInitials: 'DK',
    dateCompleted: '2026-08-09',
    timeCompleted: '08:00',
    auditStatus: 'Verified',
    dueDate: '2026-08-10',
    notes: 'Daily Radio DSC test SAT. EPIRB self test OK.',
  },
];

// Helper generator for initial sheet states
export const initialSheets: Record<string, InspectionSheetData> = {
  'fixed-fire': {
    id: 'fixed-fire',
    title: 'Fixed Fire Systems',
    subtitle: 'Complete the inspection table. Entry boxes are unlocked; formulas and headings are protected.',
    items: [
      { id: 'ff-1', name: 'CO2 ROOM CYLINDERS', amosNo: '510.00.100', criteria: 'Visual inspection; verify label/signage and access', satStatus: 'SAT' },
      { id: 'ff-2', name: 'CO2 ROOM HOSES', amosNo: '510.00.100', criteria: 'Visual inspection; verify label/signage and access', satStatus: 'SAT' },
      { id: 'ff-3', name: 'BRIDGE REMOTE (Main Gens. Port and Stbd.)', amosNo: '510.00.100', criteria: 'Visual inspection; verify label/signage and access', satStatus: 'SAT' },
      { id: 'ff-4', name: '01 FWD REMOTE (Main Gens Port and Stbd.)', amosNo: '510.00.100', criteria: 'Visual inspection; verify label/signage and access', satStatus: 'SAT' },
      { id: 'ff-5', name: '01 STBD REMOTE (Emergency Gen. and Incinerator Rm)', amosNo: '510.00.100', criteria: 'Visual inspection; verify label/signage and access', satStatus: 'SAT' },
      { id: 'ff-6', name: 'HAZMAT LOCKER REMOTE', amosNo: '510.00.100', criteria: 'Visual inspection; verify label/signage and access', satStatus: 'SAT' },
      { id: 'ff-7', name: 'STBD CHEM LAB, FIXED 1.1# CO2', amosNo: '510.00.100', criteria: 'Visual inspection; verify label/signage and access', satStatus: 'SAT' },
      { id: 'ff-8', name: 'PORT MOTOR ROOM, FIXED 20# CO2', amosNo: '510.00.100', criteria: 'Visual inspection; verify label/signage and access', satStatus: 'SAT' },
      { id: 'ff-9', name: 'STBD MOTOR ROOM, FIXED 20# CO2', amosNo: '510.00.100', criteria: 'Visual inspection; verify label/signage and access', satStatus: 'SAT' },
      { id: 'ff-10', name: 'BOW THRUSTER MOTOR, FIXED 20# CO2', amosNo: '510.00.100', criteria: 'Visual inspection; verify label/signage and access', satStatus: 'SAT' },
      { id: 'ff-11', name: 'INCINERATOR ROOM, 40 GALLON FOAM', amosNo: '510.00.100', criteria: 'Visual inspection; verify label/signage and access', satStatus: 'SAT' },
      { id: 'ff-12', name: 'GALLEY ANSUL HOOD TANK', amosNo: '510.00.100', criteria: 'Visual inspection; verify label/signage and access', satStatus: 'SAT' },
      { id: 'ff-13', name: 'GALLEY ANSUL HOOD TANK HOSES', amosNo: '510.00.100', criteria: 'Visual inspection; verify label/signage and access', satStatus: 'SAT' },
      { id: 'ff-14', name: 'GALLEY DUCTING 20# CO2', amosNo: '510.00.100', criteria: 'Visual inspection; verify label/signage and access', satStatus: 'SAT' },
      { id: 'ff-15', name: 'Charge pulls, heat links, and nozzles', amosNo: '510.00.100', criteria: 'Visual inspection; verify label/signage and access', satStatus: 'SAT' },
      { id: 'ff-16', name: 'Annual service record', amosNo: '', criteria: 'Weigh cylinders / lubricate valves / vendor service certificate', satStatus: 'SAT', comments: 'Certificate date/vendor/inspector' },
    ],
    deficiencies: [],
    signoff: { mateName: 'David K.', position: '2nd Mate', signatureInitials: 'DK', dateCompleted: '2026-07-15', timeCompleted: '10:00' },
  },

  'weekly-lifesaving': {
    id: 'weekly-lifesaving',
    title: 'Weekly Lifesaving',
    subtitle: 'Complete the inspection table. Entry boxes are unlocked; formulas and headings are protected.',
    items: [
      { id: 'wl-1', section: 'LIFE RAFTS', amosNo: '520.00.001 thru 006', name: 'LIFE RAFTS', criteria: 'Visually inspect hydrostatic release & pelican hook', satStatus: 'SAT', w1: 'SAT', w2: 'SAT', w3: 'SAT', w4: 'SAT', w5: 'SAT' },
      { id: 'wl-2', section: 'RESCUE BOAT', amosNo: '520.00.010', name: 'RESCUE BOAT', criteria: 'Check gripes, engine on transom, tube inflation, painter/tag lines, propeller, quick-release hook', satStatus: 'SAT', w1: 'SAT', w2: 'SAT', w3: 'SAT', w4: 'SAT', w5: 'SAT' },
      { id: 'wl-3', section: 'RESCUE BOAT ENGINE', amosNo: '520.00.011', name: 'RESCUE BOAT ENGINE', criteria: 'Fuel level, leaks/deterioration, run engine and flush, charge batteries', satStatus: 'SAT', w1: 'SAT', w2: 'SAT', w3: 'SAT', w4: 'SAT', w5: 'SAT' },
      { id: 'wl-4', section: 'LIFERINGS', amosNo: '530.00.002', name: 'LIFERINGS & LIFERING ATTACHMENTS', criteria: 'Inspect liferings, LifeSlings P&S, attachments', satStatus: 'SAT', w1: 'SAT', w2: 'SAT', w3: 'SAT', w4: 'SAT', w5: 'SAT' },
    ],
    deficiencies: [],
    signoff: { mateName: 'Sarah M.', position: '3rd Mate', signatureInitials: 'SM', dateCompleted: '2026-08-03', timeCompleted: '14:15' },
  },

  'lifesaving-monthly': {
    id: 'lifesaving-monthly',
    title: 'Lifesaving Monthly',
    subtitle: 'Complete the inspection table. Entry boxes are unlocked; formulas and headings are protected.',
    items: [
      { id: 'lm-1', section: 'LIFERAFTS', name: 'Liferaft 2 #520.00.002 Port', criteria: 'Condition; service due; release exp; EPIRB batt/reg exp', satStatus: 'SAT' },
      { id: 'lm-2', section: 'LIFERAFTS', name: 'Liferaft 4 #520.00.004 Port', criteria: 'Condition; service due; release exp; EPIRB batt/reg exp', satStatus: 'SAT' },
      { id: 'lm-3', section: 'LIFERAFTS', name: 'Liferaft 6 #520.00.006 Port', criteria: 'Condition; service due; release exp; EPIRB batt/reg exp', satStatus: 'SAT' },
      { id: 'lm-4', section: 'LIFERAFTS', name: 'Liferaft 1 #520.00.001 Stbd', criteria: 'Condition; service due; release exp; EPIRB batt/reg exp', satStatus: 'SAT' },
      { id: 'lm-5', section: 'LIFERAFTS', name: 'Liferaft 3 #520.00.003 Stbd', criteria: 'Condition; service due; release exp; EPIRB batt/reg exp', satStatus: 'SAT' },
      { id: 'lm-6', section: 'LIFERAFTS', name: 'Liferaft 5 #520.00.005 Stbd', criteria: 'Condition; service due; release exp; EPIRB batt/reg exp', satStatus: 'SAT' },
      { id: 'lm-7', section: 'LIFEBUOYS AND ATTACHMENTS', name: '03 Deck Port', criteria: 'Buoy, line, light, smoke, expire date', satStatus: 'SAT' },
      { id: 'lm-8', section: 'LIFEBUOYS AND ATTACHMENTS', name: '03 Deck Stbd', criteria: 'Buoy, line, light, smoke, expire date', satStatus: 'SAT' },
      { id: 'lm-9', section: 'LIFEBUOYS AND ATTACHMENTS', name: '01 Deck Port Fwd', criteria: 'Buoy, line, light, smoke, expire date', satStatus: 'SAT' },
      { id: 'lm-10', section: 'LIFEBUOYS AND ATTACHMENTS', name: '01 Deck Port Aft', criteria: 'Buoy, line, light, smoke, expire date', satStatus: 'SAT' },
      { id: 'lm-11', section: 'LIFEBUOYS AND ATTACHMENTS', name: '01 Deck Stbd Fwd', criteria: 'Buoy, line, light, smoke, expire date', satStatus: 'SAT' },
      { id: 'lm-12', section: 'LIFEBUOYS AND ATTACHMENTS', name: '01 Deck Stbd Aft', criteria: 'Buoy, line, light, smoke, expire date', satStatus: 'SAT' },
      { id: 'lm-13', section: 'LIFEBUOYS AND ATTACHMENTS', name: 'Main Deck Port', criteria: 'Buoy, line, light, smoke, expire date', satStatus: 'SAT' },
      { id: 'lm-14', section: 'LIFEBUOYS AND ATTACHMENTS', name: 'Main Deck Stbd', criteria: 'Buoy, line, light, smoke, expire date', satStatus: 'SAT' },
      { id: 'lm-15', section: 'LIFEBUOYS AND ATTACHMENTS', name: 'LifeSling Port', criteria: 'Buoy, line, light, smoke, expire date', satStatus: 'SAT' },
      { id: 'lm-16', section: 'LIFEBUOYS AND ATTACHMENTS', name: 'LifeSling Stbd', criteria: 'Buoy, line, light, smoke, expire date', satStatus: 'SAT' },
    ],
    deficiencies: [],
    signoff: { mateName: 'Sarah M.', position: '3rd Mate', signatureInitials: 'SM', dateCompleted: '2026-07-12', timeCompleted: '11:30' },
  },

  'pyrotechnics-locker': {
    id: 'pyrotechnics-locker',
    title: 'Pyrotechnics Locker',
    subtitle: 'Complete the inspection table. Entry boxes are unlocked; formulas and headings are protected.',
    items: [
      { id: 'py-1', section: 'PYROTECHNICS LOCKER', name: '(12) Red rocket parachute flares', criteria: 'Count and expiration date; seal/condition; stowage', satStatus: 'SAT', quantity: 12, expirationDate: '2028-05-31' },
      { id: 'py-2', section: 'PYROTECHNICS LOCKER', name: '(4) Line throwing apparatus', criteria: 'Count and expiration date; seal/condition; stowage', satStatus: 'SAT', quantity: 4, expirationDate: '2028-02-28' },
      { id: 'py-3', section: 'PYROTECHNICS LOCKER', name: '(4) Line throwing apparatus rockets', criteria: 'Count and expiration date; seal/condition; stowage', satStatus: 'SAT', quantity: 4, expirationDate: '2028-02-28' },
      { id: 'py-4', section: 'PYROTECHNICS LOCKER', name: '(2) Line floats', criteria: 'Count and expiration date; seal/condition; stowage', satStatus: 'SAT', quantity: 2 },
      { id: 'py-5', section: 'PYROTECHNICS LOCKER', name: '(2) Gloves / (1) Goggles', criteria: 'Count and expiration date; seal/condition; stowage', satStatus: 'SAT', quantity: '2 gloves / 1 goggles' },
      { id: 'py-6', section: 'BRIDGE PYROTECHNICS', name: 'Bridge pyrotechnics', criteria: 'Count, condition, and expiry for parachute/smoke/hand flares where carried', satStatus: 'SAT' },
      { id: 'py-7', section: 'LINE THROWING', name: 'Line throwing appliances', criteria: 'Count, condition, rocket expiry, lines/floats/gloves/goggles', satStatus: 'SAT' },
    ],
    deficiencies: [],
    signoff: { mateName: 'David K.', position: '2nd Mate', signatureInitials: 'DK', dateCompleted: '2026-07-14', timeCompleted: '09:00' },
  },

  'rescue-boat': {
    id: 'rescue-boat',
    title: 'Rescue Boat Monthly',
    subtitle: 'Complete the inspection table. Entry boxes are unlocked; formulas and headings are protected.',
    items: [
      { id: 'rb-1', section: 'Equipment', name: 'Anchor', quantity: '1', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT', comments: 'Chain and rope' },
      { id: 'rb-2', section: 'Equipment', name: 'Bailer', quantity: '1', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-3', section: 'Equipment', name: 'First Aid Kit', quantity: '1', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT', comments: 'Yellow bag' },
      { id: 'rb-4', section: 'Equipment', name: 'Flashlight', quantity: '1', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-5', section: 'Equipment', name: 'Heaving line w/ quoit', quantity: '3', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-6', section: 'Equipment', name: 'Knife', quantity: '1', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-7', section: 'Equipment', name: 'Ladder', quantity: '1', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-8', section: 'Equipment', name: 'Bucket', quantity: '1', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-9', section: 'Equipment', name: 'Sea anchor', quantity: '1', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-10', section: 'Equipment', name: 'Sponge', quantity: '2', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-11', section: 'Equipment', name: 'Thermal protective aid', quantity: '3', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-12', section: 'Equipment', name: 'Tool kit', quantity: '1', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-13', section: 'Equipment', name: 'Tow line', quantity: '3', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-14', section: 'Equipment', name: 'Whistle', quantity: '1', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-15', section: 'Equipment', name: 'Fog horn', quantity: '1', where: 'Helm', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-16', section: 'Equipment', name: 'Water bottles', quantity: '6', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT', comments: 'Replace per vessel practice' },
      { id: 'rb-17', section: 'Equipment', name: 'Ratchet straps', quantity: '2', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-18', section: 'Equipment', name: 'Funnel', quantity: '1', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-19', section: 'Equipment', name: 'Engineering manuals', quantity: '1 bag', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-20', section: 'Equipment', name: 'Handheld red flares', quantity: '6', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT', comments: 'Keep sealed; exp 2028' },
      { id: 'rb-21', section: 'Equipment', name: 'Handheld orange smoke', quantity: '6', where: 'FWD Compartment', criteria: 'Inventory and condition', satStatus: 'SAT', comments: 'Keep sealed; exp 2028' },
      { id: 'rb-22', section: 'Equipment', name: 'Boat hook', quantity: '2', where: 'Above seats', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-23', section: 'Equipment', name: 'Fire extinguisher 10# dry chem', quantity: '1', where: 'STBD side aft', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-24', section: 'Equipment', name: 'Paddles', quantity: '2', where: 'Above seats', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-25', section: 'Equipment', name: 'Radar reflector', quantity: '1', where: 'STBD AFT', criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'rb-26', section: 'Equipment', name: 'Search light', quantity: '1', where: 'STBD Console', criteria: 'Inventory and condition', satStatus: 'UNSAT', comments: 'Cracked lens, water inside' },
      { id: 'rb-27', section: 'Equipment', name: 'Compass', quantity: '1', where: 'Helm', criteria: 'Inventory and condition', satStatus: 'SAT' },
      // Operational checks
      { id: 'rb-op-1', section: 'Operational Check', name: 'Required onboard items checked against inventory sheet', criteria: 'Inspect / test / record date where applicable', satStatus: 'SAT' },
      { id: 'rb-op-2', section: 'Operational Check', name: 'Test gauges / fuel gauge or dipstick', criteria: 'Inspect / test / record date where applicable', satStatus: 'SAT' },
      { id: 'rb-op-3', section: 'Operational Check', name: 'Test bilge pumps manual and automatic; inspect compartments for water ingress', criteria: 'Inspect / test / record date where applicable', satStatus: 'SAT' },
      { id: 'rb-op-4', section: 'Operational Check', name: 'Check navigation lights', criteria: 'Inspect / test / record date where applicable', satStatus: 'SAT' },
      { id: 'rb-op-5', section: 'Operational Check', name: 'Test spot light', criteria: 'Inspect / test / record date where applicable', satStatus: 'SAT' },
      { id: 'rb-op-6', section: 'Operational Check', name: 'Check painter/tag lines', criteria: 'Inspect / test / record date where applicable', satStatus: 'SAT' },
      { id: 'rb-op-7', section: 'Operational Check', name: 'Check fenders for damage/deformation', criteria: 'Inspect / test / record date where applicable', satStatus: 'SAT' },
      { id: 'rb-op-8', section: 'Operational Check', name: 'Inspect life lines and reflective material', criteria: 'Inspect / test / record date where applicable', satStatus: 'SAT' },
      { id: 'rb-op-9', section: 'Operational Check', name: 'Check self-righting system', criteria: 'Inspect / test / record date where applicable', satStatus: 'SAT' },
      { id: 'rb-op-10', section: 'Operational Check', name: 'Fuel tank level', criteria: 'Inspect / test / record date where applicable', satStatus: 'SAT', comments: 'Full (100%)' },
      { id: 'rb-op-11', section: 'Operational Check', name: 'Engine oil level & cooling water level', criteria: 'Inspect / test / record date where applicable', satStatus: 'SAT' },
      { id: 'rb-op-12', section: 'Operational Check', name: 'Batteries connections & start battery date', criteria: 'Inspect / test / record date where applicable', satStatus: 'SAT' },
      { id: 'rb-op-13', section: 'Operational Check', name: 'Test release hook and lubricate as required', criteria: 'Inspect / test / record date where applicable', satStatus: 'SAT' },
      { id: 'rb-op-14', section: 'Operational Check', name: 'Overall condition', criteria: 'Inspect / test / record date where applicable', satStatus: 'SAT' },
    ],
    deficiencies: [
      {
        id: 'DEF-2026-001',
        dateFound: '2026-07-10',
        inspectionId: 'rescue-boat',
        inspectionTitle: 'Rescue Boat Monthly',
        deficiency: 'Rescue boat search light lens cracked; water condensation inside housing',
        priority: 'Medium',
        workOrder: 'WO-88210',
        assignedTo: 'Deck Dept - 3rd Mate',
        dueDate: '2026-08-15',
        dateCorrected: '',
        verifiedBy: '',
        status: 'In Progress',
        notes: 'Replacement housing ordered from vendor. Temporary seal applied.',
        initials: 'SM',
      }
    ],
    signoff: { mateName: 'Sarah M.', position: '3rd Mate', signatureInitials: 'SM', dateCompleted: '2026-07-10', timeCompleted: '13:00' },
  },

  'lifejackets-immersion': {
    id: 'lifejackets-immersion',
    title: 'Lifejackets Immersion',
    subtitle: 'Complete the inspection table. Entry boxes are unlocked; formulas and headings are protected.',
    items: [
      { id: 'lji-1', name: '03 DECK Pilot House', pfdCount: 3, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-2', name: '02-01', pfdCount: 1, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-3', name: '02-02', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-4', name: '02-03', pfdCount: 1, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-5', name: '02-04', pfdCount: 1, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-6', name: '02-05', pfdCount: 1, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-7', name: '02-06', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-8', name: '02-08', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-9', name: '02-10', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-10', name: '02-12', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-11', name: '02-14', pfdCount: 1, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-12', name: '02-16', pfdCount: 1, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-13', name: 'Hospital', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-14', name: '01-01', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-15', name: '01-02', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-16', name: '01-03', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-17', name: '01-04', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-18', name: '01-05', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-19', name: '01-06', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-20', name: 'MCS', pfdCount: 1, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-21', name: '01-07', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-22', name: '01-08', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-23', name: '01-09', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-24', name: '01-10', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-25', name: '01-11', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-26', name: '01-12', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-27', name: '01-13', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-28', name: '01-14', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-29', name: '01-15', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-30', name: '01-16', pfdCount: 2, criteria: 'Verify present, accessible, lights/whistles/condition as applicable', satStatus: 'SAT' },
      { id: 'lji-31', name: 'SPARES - 3/M Locker', pfdCount: 12, criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'lji-32', name: 'SPARES - Sci Stores #1', pfdCount: 11, criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'lji-33', name: 'SPARES - Universal', suitCount: 6, criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'lji-34', name: 'SPARES - Oversized', suitCount: 5, criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'lji-35', name: 'SPARES - Small', suitCount: 1, criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'lji-36', name: 'SPARES - Child', suitCount: 2, criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'lji-37', name: 'SPARES - 03 Deck spares', pfdCount: 3, suitCount: 3, criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'lji-38', name: 'SPARES - 02 Deck spares', pfdCount: 18, suitCount: 18, criteria: 'Inventory and condition', satStatus: 'SAT' },
      { id: 'lji-39', name: 'SPARES - 01 Deck spares', pfdCount: 35, suitCount: 35, criteria: 'Inventory and condition', satStatus: 'SAT' },
    ],
    deficiencies: [],
    signoff: { mateName: 'Sarah M.', position: '3rd Mate', signatureInitials: 'SM', dateCompleted: '2026-07-16', timeCompleted: '15:20' },
  },

  'dewatering-pumps': {
    id: 'dewatering-pumps',
    title: 'De-Watering Pumps',
    subtitle: 'Complete the inspection table. Entry boxes are unlocked; formulas and headings are protected.',
    items: [
      { id: 'dw-1', name: 'PROSSER 1', where: 'SCI. STO. RM #1', amosNo: '560.00.003', modelNo: '9-25134-04', serialNo: 'C1565497-0212', partNo: '2-33241', capacity: 'H/H 155 GPM', criteria: 'Pumps, hoses, strainers, fuel/oil, and operational test', fuelOilCheck: 'SAT', hosesStrainersCheck: 'SAT', operationalTestCheck: 'SAT', satStatus: 'SAT' },
      { id: 'dw-2', name: 'PROSSER 2', where: 'SCI. STO. RM #1', amosNo: '560.00.004', modelNo: '9-25134-04', serialNo: 'C1565498-0212', capacity: 'H/H 155 GPM', criteria: 'Pumps, hoses, strainers, fuel/oil, and operational test', fuelOilCheck: 'SAT', hosesStrainersCheck: 'UNSAT', operationalTestCheck: 'SAT', satStatus: 'UNSAT', comments: 'Discharge hose gasket leaking slightly' },
      { id: 'dw-3', name: 'PROSSER 3', where: 'SCI. STO. RM #1', amosNo: '560.00.005', modelNo: '9-25134-54', serialNo: 'C1565499-0212', capacity: 'H/V 310 GPM', criteria: 'Pumps, hoses, strainers, fuel/oil, and operational test', fuelOilCheck: 'SAT', hosesStrainersCheck: 'SAT', operationalTestCheck: 'SAT', satStatus: 'SAT' },
      { id: 'dw-4', name: 'PROSSER 4', where: 'SCI. STO. RM #1', amosNo: '560.00.006', modelNo: '9-25134-54', serialNo: 'C1565500-0212', partNo: '2-33241', capacity: 'H/V 310 GPM', criteria: 'Pumps, hoses, strainers, fuel/oil, and operational test', fuelOilCheck: 'SAT', hosesStrainersCheck: 'SAT', operationalTestCheck: 'SAT', satStatus: 'SAT' },
      { id: 'dw-5', name: 'PACER/DIESEL 5', where: 'SCI. STO. RM #1', amosNo: '560.00.001', modelNo: 'SE2RL E5DLC', serialNo: '283633', capacity: '250 GPM', criteria: 'Pumps, hoses, strainers, fuel/oil, and operational test', fuelOilCheck: 'SAT', hosesStrainersCheck: 'SAT', operationalTestCheck: 'SAT', satStatus: 'SAT' },
      { id: 'dw-6', name: 'PACER/DIESEL 6', where: 'SCI. STO. RM #1', amosNo: '560.00.002', modelNo: 'SE2RL E5DLC', capacity: '250 GPM', criteria: 'Pumps, hoses, strainers, fuel/oil, and operational test', fuelOilCheck: 'SAT', hosesStrainersCheck: 'SAT', operationalTestCheck: 'SAT', satStatus: 'SAT' },
    ],
    deficiencies: [
      {
        id: 'DEF-2026-002',
        dateFound: '2026-07-08',
        inspectionId: 'dewatering-pumps',
        inspectionTitle: 'De-Watering Pumps',
        deficiency: 'PROSSER 2 pump discharge hose gasket worn and leaking slightly during pressure test',
        priority: 'High',
        workOrder: 'WO-88194',
        assignedTo: 'Eng Dept - 1st Asst',
        dueDate: '2026-08-05',
        dateCorrected: '',
        verifiedBy: '',
        status: 'Open',
        notes: 'Overdue for resolution. Gasket replacement in stock in sci stores.',
        initials: 'RK',
      }
    ],
    signoff: { mateName: 'Robert K.', position: '1st Asst Engineer', signatureInitials: 'RK', dateCompleted: '2026-07-08', timeCompleted: '11:00' },
  },

  'fire-stations': {
    id: 'fire-stations',
    title: 'Fire Stations',
    subtitle: 'Complete the inspection table. Entry boxes are unlocked; formulas and headings are protected.',
    items: [
      { id: 'fs-1', name: 'Station 1', where: '03 AFT BRIDGE', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-2', name: 'Station 2', where: '02 MIDSHIPS AFT OF 02-05', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-3', name: 'Station 3', where: '02 FWD DOG HOUSE', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-4', name: 'Station 4', where: '01 FWD PORT & INTERNATIONAL SHORE CONNECTION', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-5', name: 'Station 5', where: '01 FWD STBD & INTERNATIONAL SHORE CONNECTION', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-6', name: 'Station 6', where: '01 FWD MIDSHIPS PASSAGEWAY', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-7', name: 'Station 7', where: '01 AFT MIDSHIPS PASSAGEWAY', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-8', name: 'Station 8', where: 'MAIN PORT MESS', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-9', name: 'Station 9', where: 'MAIN STBD MESS', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-10', name: 'Station 10', where: 'MAIN PORT MIDSHIPS OUTSIDE DOOR TO SWITCHBOARD', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-11', name: 'Station 11', where: 'MAIN STBD GENS', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-12', name: 'Station 12', where: 'MAIN PORT GENS', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-13', name: 'Station 13', where: 'MAIN STBD SCI STRM #3', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-14', name: 'Station 14', where: 'MAIN PORT SCI STRM #2', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-15', name: 'Station 15', where: 'MAIN STBD CHEM LAB', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-16', name: 'Station 16', where: 'MAIN PORT LAB #2', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-17', name: 'Station 17', where: 'MAIN STBD HYDRO LAB', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-18', name: 'Station 18', where: 'MAIN PORT WINCH ROOM', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-19', name: 'Station 19', where: 'MAIN AFT MIDSHIPS', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-20', name: 'Station 20', where: 'FLAT 1 PORT GALLEY STRM #2', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-21', name: 'Station 21', where: 'FLAT 1 STBD GALLEY STRM #1', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-22', name: 'Station 22', where: 'FLAT 1 PORT GSM #2', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-23', name: 'Station 23', where: 'FLAT 1 STBD DRY STORES #1', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-24', name: 'Station 24', where: 'FLAT 1 PORT MACHINERY RM #4', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-25', name: 'Station 25', where: 'FLAT 1 STBD MACHINERY RM #3', criteria: '2.5 x 50 hose; 1.5 x 50/75 hose; nozzles; caps; spanner; axe', satStatus: 'SAT' },
      { id: 'fs-hydro', name: 'Hose Hydrostatic Test', where: 'All Stations', criteria: 'Hydrostatic test of hoses date / Next hydrostatic test due', satStatus: 'SAT', hydroDate: '2026-02-15', expirationDate: '2027-02-15' },
    ],
    deficiencies: [],
    signoff: { mateName: 'David K.', position: '2nd Mate', signatureInitials: 'DK', dateCompleted: '2026-07-18', timeCompleted: '09:45' },
  },

  'turnout-gear': {
    id: 'turnout-gear',
    title: 'Turnout Gear SCBA',
    subtitle: 'Complete the inspection table. Entry boxes are unlocked; formulas and headings are protected.',
    items: [
      { id: 'tg-1', section: 'PACK A', name: 'Jackets, Pants, Boots, Gloves, Hood, Helmet, Flashlight, Lifeline, Lifebelt, Axe, Headlamp', criteria: 'Condition / exp date where applicable', satStatus: 'SAT' },
      { id: 'tg-2', section: 'PACK B', name: 'Jackets, Pants, Boots, Gloves, Hood, Helmet, Flashlight, Lifeline, Lifebelt, Axe, Headlamp', criteria: 'Condition / exp date where applicable', satStatus: 'SAT' },
      { id: 'tg-3', section: 'PACK C', name: 'Jackets, Pants, Boots, Gloves, Hood, Helmet, Flashlight, Lifeline, Lifebelt, Axe, Headlamp', criteria: 'Condition / exp date where applicable', satStatus: 'SAT' },
      { id: 'tg-4', section: 'PACK D', name: 'Jackets, Pants, Boots, Gloves, Hood, Helmet, Flashlight, Lifeline, Lifebelt, Axe, Headlamp', criteria: 'Condition / exp date where applicable', satStatus: 'SAT' },
      { id: 'tg-5', section: 'PACK E', name: 'Jackets, Pants, Boots, Gloves, Hood, Helmet, Flashlight, Lifeline, Lifebelt, Axe, Headlamp', criteria: 'Condition / exp date where applicable', satStatus: 'SAT' },
      { id: 'tg-6', section: 'PACK F', name: 'Jackets, Pants, Boots, Gloves, Hood, Helmet, Flashlight, Lifeline, Lifebelt, Axe, Headlamp', criteria: 'Condition / exp date where applicable', satStatus: 'SAT' },
      { id: 'tg-mg1', section: 'MULTIGAS ANALYZER', name: 'MX4-(fwd)', amosNo: '530.00.010', criteria: 'Calibrated, tested, charge date, gas bottle PSI/exp', satStatus: 'SAT', comments: 'Added per SMS discussion' },
      { id: 'tg-mg2', section: 'MULTIGAS ANALYZER', name: 'MX4-(aft)', amosNo: '530.00.010', criteria: 'Calibrated, tested, charge date, gas bottle PSI/exp', satStatus: 'SAT', comments: 'Added per SMS discussion' },
      { id: 'tg-scba1', section: 'SCBA', name: 'PACK A / B / C', amosNo: '510.00.204/205', criteria: 'PSI, hydro date/due, flash hood, condition', satStatus: 'SAT' },
      { id: 'tg-scba2', section: 'SCBA', name: 'SPARE A / B / C', amosNo: '510.00.204/205', criteria: 'PSI, hydro date/due, flash hood, condition', satStatus: 'SAT' },
      { id: 'tg-scba3', section: 'SCBA', name: 'PACK D / E / F', amosNo: '510.00.204/205', criteria: 'PSI, hydro date/due, flash hood, condition', satStatus: 'SAT' },
      { id: 'tg-scba4', section: 'SCBA', name: 'SPARE D / E / F', amosNo: '510.00.204/205', criteria: 'PSI, hydro date/due, flash hood, condition', satStatus: 'SAT' },
      { id: 'tg-scba5', section: 'SCBA', name: 'SPARE IN 3/M STORES', amosNo: '510.00.204/205', criteria: 'PSI, hydro date/due, flash hood, condition', satStatus: 'SAT' },
      { id: 'tg-scba6', section: 'SCBA', name: 'TRAINER BOTTLE', amosNo: '510.00.204/205', criteria: 'PSI, hydro date/due, flash hood, condition', satStatus: 'SAT' },
    ],
    deficiencies: [],
    signoff: { mateName: 'David K.', position: '2nd Mate', signatureInitials: 'DK', dateCompleted: '2026-07-11', timeCompleted: '14:00' },
  },

  'damage-control': {
    id: 'damage-control',
    title: 'Damage Control Gear',
    subtitle: 'Complete the inspection table. Entry boxes are unlocked; formulas and headings are protected.',
    items: [
      { id: 'dc-1', section: '01 DECK DC LOCKER PORT', name: 'Firemans outfits A,B,C, SCBA Packs/Spares A,B,C, Fire Hoses, Y Gate, Nozzles, Eductor, Axe, Plugs/Wedges', criteria: 'Present and serviceable', satStatus: 'SAT' },
      { id: 'dc-2', section: '01 DECK NOT IN DC LOCKER', name: 'Foam nozzle & pick-up tube, 5 gal AFFF 3% foam containers', criteria: 'Present and serviceable', satStatus: 'SAT' },
      { id: 'dc-3', section: 'MAIN DECK DC LOCKER AFT PORT', name: 'Firemans outfits D,E,F, SCBA Packs/Spares D,E,F, Hoses, Y Gate, Nozzles, Axe, Radios, Multigas', criteria: 'Present and serviceable', satStatus: 'SAT' },
      { id: 'dc-4', section: 'MAIN DECK NOT IN DC LOCKERS', name: 'Foam nozzles, Sked evacuation kit with basket backboard, Dewatering hoses & extension cords', criteria: 'Present and serviceable', satStatus: 'SAT' },
      { id: 'dc-5', section: 'SCIENCE STORE ROOM 1', name: 'HH 155gpm Pump No.1 & No.2, HV 310gpm Pump No.3 & No.4, Electrical rubber gloves', criteria: 'Present and serviceable', satStatus: 'SAT' },
    ],
    deficiencies: [],
    signoff: { mateName: 'James L.', position: 'Chief Mate', signatureInitials: 'JL', dateCompleted: '2026-07-20', timeCompleted: '11:15' },
  },

  'fire-extinguishers': {
    id: 'fire-extinguishers',
    title: 'Fire Extinguishers',
    subtitle: 'Complete the inspection table. Entry boxes are unlocked; formulas and headings are protected.',
    items: [
      { id: 'fe-1', name: '1', amosNo: '10# DRY CHEM', where: 'PILOT HOUSE - STBD', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-2', name: '2', amosNo: '10# DRY CHEM', where: 'PILOT HOUSE - PORT', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-3', name: '3', amosNo: '5# CO2', where: 'CHARTROOM', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-4', name: '4', amosNo: '10# DRY CHEM', where: 'FIRE STATION 2', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-5', name: '5', amosNo: '20# DRY CHEM', where: 'FWD PASSAGEWAY - STBD', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-6', name: '6', amosNo: '20# DRY CHEM', where: 'AFT PASSAGEWAY', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-7', name: '7', amosNo: '10# DRY CHEM', where: 'LOUNGE PASSAGEWAY', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-8', name: '8', amosNo: '10# DRY CHEM', where: 'FIRE STATION 6', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-9', name: '9', amosNo: '5# CO2', where: 'STAIRWAY TO AMR-1', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-10', name: '10', amosNo: '15# CO2', where: 'WORKSHOP', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-11', name: '11', amosNo: '15# CO2', where: 'MCS - PORT', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-12', name: '12', amosNo: '5# CO2', where: 'MCS - FWD', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-13', name: '13', amosNo: '15# CO2', where: 'COMPUTER LAB - STBD', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-14', name: '14', amosNo: '5# CO2', where: 'COMPUTER LAB - STBD', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-15', name: '15', amosNo: '2.5 GAL FOAM', where: 'INCINERATOR ROOM', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-16', name: '16', amosNo: '10# DRY CHEM', where: 'INCINERATOR ROOM', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-17', name: '17', amosNo: '2.5 GAL FOAM', where: 'EMERGENCY GEN ROOM', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-18', name: '18', amosNo: '10# DRY CHEM', where: 'FIRE STATION 7', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-19', name: '19', amosNo: '10# DRY CHEM', where: 'OUTSIDE S/R 01-16', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-20', name: '20', amosNo: '10# DRY CHEM', where: 'OUTSIDE S/R 01-13', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-21', name: '21', amosNo: '5# CO2', where: 'CRANE - PORT', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-22', name: '22', amosNo: '5# CO2', where: 'ET LOCKER', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-23', name: '23', amosNo: '10# DRY CHEM', where: 'I-MET LAB', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-24', name: '24', amosNo: '15# CO2', where: 'MESSDECK - PORT', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-25', name: '25', amosNo: '15# CO2', where: 'MESSDECK - STBD', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-26', name: '26', amosNo: '15# CO2', where: 'LAUNDRY ROOM - STBD', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-27', name: '27', amosNo: '10# DRY CHEM', where: 'GALLEY - PORT', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-28', name: '28', amosNo: '5# CO2', where: 'GALLEY - PORT', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-75', name: '75', amosNo: '20# WET CHEM', where: 'GALLEY - PORT', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-29', name: '29', amosNo: '15# CO2', where: 'GALLEY - STBD', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-30', name: '30', amosNo: '10# DRY CHEM', where: 'STORES', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-31', name: '31', amosNo: '10# DRY CHEM', where: 'GENERATOR ROOM 2 - FWD', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-32', name: '32', amosNo: '15# CO2', where: 'GENERATOR ROOM 2 - MID', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-33', name: '33', amosNo: '20# DRY CHEM', where: 'GENERATOR ROOM 2 - AFT', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-34', name: '34', amosNo: '15# CO2', where: 'AMR-1 AFT', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-35', name: '35', amosNo: '2.5 GAL FOAM', where: 'AMR-1 FWD', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-36', name: '36', amosNo: '10# DRY CHEM', where: 'GENERATOR ROOM 1 - FWD', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-37', name: '37', amosNo: '15# CO2', where: 'GENERATOR ROOM 1 - MID', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', satStatus: 'SAT' },
      { id: 'fe-38', name: '38', amosNo: '20# DRY CHEM', where: 'GENERATOR ROOM 1 - AFT', criteria: 'Gauge/weight, seal, pin, hose/nozzle, placard, access, mount, service/hydro dates', dryChemRotated: 'Yes', satStatus: 'SAT' },
      { id: 'fe-s1', name: 'S1-S18 Spares', amosNo: '5# CO2 / 10# DRY CHEM / 15# CO2 / FOAM', where: 'SPARES (Aft Control, DC Locker, CO2 Room)', criteria: 'Spare extinguisher condition and service date', dryChemRotated: 'Yes', satStatus: 'SAT' },
    ],
    deficiencies: [],
    signoff: { mateName: 'David K.', position: '2nd Mate', signatureInitials: 'DK', dateCompleted: '2026-07-13', timeCompleted: '16:00' },
  },

  'dg-locker': {
    id: 'dg-locker',
    title: 'DG Locker Monthly',
    subtitle: 'Complete the inspection table. Entry boxes are unlocked; formulas and headings are protected.',
    items: [
      { id: 'dg-1', section: 'Area / Item', name: 'DG/Hazmat Locker', criteria: 'Access clear, placards/signage legible, ventilation/housekeeping satisfactory', satStatus: 'SAT' },
      { id: 'dg-2', section: 'Area / Item', name: 'Segregation / compatibility', criteria: 'Materials segregated and secured per vessel procedure; no leakage/damaged packages', satStatus: 'SAT' },
      { id: 'dg-3', section: 'Area / Item', name: 'Spill response', criteria: 'Absorbent, PPE, disposal bags, and response instructions present/serviceable', satStatus: 'SAT' },
      { id: 'dg-4', section: 'Area / Item', name: 'Fixed CO2 system', criteria: 'Hazmat locker remote/manual station, signage, siren, bottle/hose/valve condition', satStatus: 'SAT' },
      { id: 'dg-5', section: 'Area / Item', name: 'Portable extinguishers', criteria: 'Hazmat locker extinguisher(s) present, mounted, charged, service date current; dry chem rotated if applicable', satStatus: 'SAT' },
      { id: 'dg-6', section: 'Area / Item', name: 'Inventory / SDS', criteria: 'Inventory current; SDS available for carried dangerous goods', satStatus: 'SAT' },
      { id: 'dg-7', section: 'Area / Item', name: 'Lighting / electrical', criteria: 'Lighting operational; no exposed wiring or ignition hazards noted', satStatus: 'SAT' },
    ],
    deficiencies: [],
    signoff: { mateName: 'James L.', position: 'Chief Mate', signatureInitials: 'JL', dateCompleted: '2026-07-19', timeCompleted: '08:45' },
  },

  'eebd': {
    id: 'eebd',
    title: 'EEBD',
    subtitle: 'Complete the inspection table. Entry boxes are unlocked; formulas and headings are protected.',
    items: [
      { id: 'ee-1', name: 'PASSAGEWAY CORNER NEAR HOSPITAL', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-2', name: 'PASSAGEWAY FWD MIDSHIP', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-3', name: 'PORT STAIRWELL TO MESSDECK', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-4', name: 'STBD STAIRWELL TO MESSDECK', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-5', name: 'MAIN CONTROL STATION', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-6', name: 'MACHINESHOP', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-7', name: 'PORT PASSAGEWAY CORNER NEAR S/R 01-08', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-8', name: 'STBD PASSAGEWAY CORNER NEAR EXERCISE ROOM', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-9', name: 'EMERGENCY GEN ROOM', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-10', name: 'INBOARD BULKHEAD PORT GEN ROOM', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-11', name: 'FWD BULKHEAD STBD GEN ROOM', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-12', name: 'STAGING BAY - NEAR LAB#2 DOOR', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-13', name: 'EYEWASH STATION - OUTSIDE CHEM LAB', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-14', name: 'HAZMAT LOCKER', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-15', name: 'GSM#2 (SEWAGE SYSTEM ROOM)', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-16', name: 'MACHINERY ROOM #2 (POTABLE H20 FLAT)', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-17', name: 'MACHINERY ROOM #1 (REFRIGERATION FLAT)', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-18', name: 'PORT CANARD ROOM / STBD CANARD ROOM', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-19', name: 'PORT PUMP ROOM / STBD PUMP ROOM', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-20', name: 'PORT MOTOR ROOM / STBD MOTOR ROOM', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-21', name: 'PORT SONAR ROOM / STBD SONAR ROOM', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-22', name: '01 DECK CABINS (01-01 to 01-18)', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
      { id: 'ee-23', name: '02 DECK CABINS (02-01 to 02-16)', criteria: 'Properly located; needle in green; exp date; condition', satStatus: 'SAT' },
    ],
    deficiencies: [],
    signoff: { mateName: 'Sarah M.', position: '3rd Mate', signatureInitials: 'SM', dateCompleted: '2026-07-17', timeCompleted: '14:30' },
  },

  'eyewash-firstaid': {
    id: 'eyewash-firstaid',
    title: 'Eye Wash Decon First Aid',
    subtitle: 'Complete the inspection table. Entry boxes are unlocked; formulas and headings are protected.',
    items: [
      { id: 'ew-1', name: 'BRIDGE', criteria: 'Exp date; unopened; sat/restock; condition', satStatus: 'SAT' },
      { id: 'ew-2', name: 'GENERATOR RM 1 & 2', criteria: 'Exp date; unopened; sat/restock; condition', satStatus: 'SAT' },
      { id: 'ew-3', name: 'HAZMAT LOCKER', criteria: 'Exp date; unopened; sat/restock; condition', satStatus: 'SAT' },
      { id: 'ew-4', name: 'GALLEY', criteria: 'Exp date; unopened; sat/restock; condition', satStatus: 'SAT' },
      { id: 'ew-5', name: 'LAB 2 / HYDRO LAB / CHEM LAB', criteria: 'Exp date; unopened; sat/restock; condition', satStatus: 'SAT' },
      { id: 'ew-6', name: 'MACHINE SHOP', criteria: 'Exp date; unopened; sat/restock; condition', satStatus: 'SAT' },
      { id: 'ew-7', name: 'WET LAB / COMPUTER LAB / LAB 1', criteria: 'Exp date; unopened; sat/restock; condition', satStatus: 'SAT' },
      { id: 'ew-8', name: 'ET LOCKER / OUTSIDE HOSPITAL / I-MET LAB', criteria: 'Exp date; unopened; sat/restock; condition', satStatus: 'SAT' },
      { id: 'ew-9', name: 'WASHDOWN STATION OUTSIDE CHEM LAB', criteria: 'Adequate water flow; chain/spring/mechanical parts; overall condition', satStatus: 'SAT' },
      { id: 'ew-10', name: 'EYE WASH STATION MACHINE SHOP', criteria: 'Adequate water flow; chain/spring/mechanical parts; overall condition', satStatus: 'SAT' },
      { id: 'ew-11', name: 'EYE WASH STATION LAB 2', criteria: 'Adequate water flow; chain/spring/mechanical parts; overall condition', satStatus: 'SAT' },
    ],
    deficiencies: [],
    signoff: { mateName: 'Dr. E. Vance', position: 'Medical Officer', signatureInitials: 'EV', dateCompleted: '2026-07-22', timeCompleted: '10:15' },
  },

  'watertight-doors': {
    id: 'watertight-doors',
    title: 'Watertight Doors',
    subtitle: 'Complete the inspection table. Entry boxes are unlocked; formulas and headings are protected.',
    items: [
      { id: 'wtd-1', name: 'Watertight doors and hatches', criteria: 'Visual inspection and operational test; dogs/gaskets/labels/access', satStatus: 'SAT' },
      { id: 'wtd-2', name: 'General alarm', criteria: 'Test general alarm; verify audible throughout required spaces', satStatus: 'SAT' },
      { id: 'wtd-3', name: 'Public address system', criteria: 'Test PA announcements or routine system test per vessel procedure', satStatus: 'SAT' },
      { id: 'wtd-4', name: 'Emergency lighting', criteria: 'Test automatic/emergency lighting transition or battery condition per vessel procedure', satStatus: 'SAT' },
      { id: 'wtd-5', name: 'Emergency power systems', criteria: 'Record emergency generator/battery test reference or engine log entry', satStatus: 'SAT' },
      { id: 'wtd-6', name: 'Corrective actions', criteria: 'Record discrepancies and work order/reference', satStatus: 'SAT' },
    ],
    deficiencies: [],
    signoff: { mateName: 'James L.', position: 'Chief Mate', signatureInitials: 'JL', dateCompleted: '2026-08-04', timeCompleted: '09:30' },
  },

  'gmdss-bridge': {
    id: 'gmdss-bridge',
    title: 'GMDSS Bridge Safety',
    subtitle: 'Complete the inspection table. Entry boxes are unlocked; formulas and headings are protected.',
    items: [
      { id: 'gmdss-1', name: 'GMDSS radios', criteria: 'Daily/weekly/monthly test per radio log; record result and log reference', satStatus: 'SAT' },
      { id: 'gmdss-2', name: 'VHF/MF/HF DSC', criteria: 'Self-test/check per vessel radio procedure', satStatus: 'SAT' },
      { id: 'gmdss-3', name: 'Satellite communications', criteria: 'Test/status check where installed', satStatus: 'SAT' },
      { id: 'gmdss-4', name: 'SARTs', criteria: 'Battery exp and self-test/status', satStatus: 'SAT' },
      { id: 'gmdss-5', name: 'EPIRB', criteria: 'Battery exp, registration exp, hydrostatic release exp, self-test/log ref', satStatus: 'SAT' },
      { id: 'gmdss-6', name: 'Bridge pyrotechnics', criteria: 'Count, condition, expiry for parachute/smoke/hand flares where carried', satStatus: 'SAT' },
      { id: 'gmdss-7', name: 'Line throwing appliances', criteria: 'Count, condition, rocket expiry, lines/floats/gloves/goggles', satStatus: 'SAT' },
      { id: 'gmdss-8', name: 'Recordkeeping', criteria: 'Confirm radio log / bridge log entry complete', satStatus: 'SAT' },
    ],
    deficiencies: [],
    signoff: { mateName: 'David K.', position: '2nd Mate', signatureInitials: 'DK', dateCompleted: '2026-08-09', timeCompleted: '08:00' },
  },
};

export const initialDatabase: AppDatabase = {
  masterCalendar: initialMasterCalendar,
  sheets: initialSheets,
  deficiencyLog: initialDeficiencyLog,
  certificateRegister: initialCertificateRegister,
  auditLog: initialAuditLog,
  binderSummary: {
    monthStart: '2026-08-01',
    totalInspections: 16,
    completedThisMonth: 3,
    dueWithin4Days: 6,
    overdue: 1,
    openDeficiencies: 2,
    certsDue30Days: 4,
  },
  connectedUsers: [
    { id: 'usr-1', name: 'Capt. Walker', role: 'Master / Captain', device: 'Bridge Workstation (Desktop)', currentSheet: 'Compliance Dashboard', lastActive: 'Just now' },
    { id: 'usr-2', name: 'James L.', role: 'Chief Mate', device: 'iPad Pro (Deck Tablet)', currentSheet: 'Rescue Boat Monthly', lastActive: '2 mins ago' },
  ],
  systemLogs: [
    { timestamp: '2026-08-09 17:00', user: 'David K. (2nd Mate)', action: 'Completed GMDSS Bridge Safety daily inspection' },
    { timestamp: '2026-08-04 09:30', user: 'James L. (Chief Mate)', action: 'Signed off Watertight Doors weekly inspection' },
  ]
};
